##########
# collectionbuilder-gh
# Jekyll Digital Collection Generator, designed for GitHub Pages
# https://github.com/CollectionBuilder/collectionbuilder-gh
##########

##########
# URL VARIABLES [optional if using GitHub Pages!]
#
# url is site domain, full URL to the production location of your collection
# on GitHub Pages follows the pattern username.github.io
#url: https://collectionbuilder.github.io 
# baseurl is path to location on the domain if necessary e.g. /digital/hjccc
# on GitHub Pages it is your github repository's name prefixed with a /
#baseurl: /collectionbuilder-gh 
# location of code, the full url to your github repository
source-code: https://github.com/CollectionBuilder/collectionbuilder-gh

##########
# SITE SETTINGS
#
# title of site appears in banner
title: Tea Time
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: A collection of artifacts that relate to tea in our culture
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "My collection focuses on my personal collection of tea and tea memorabilia. Exploring my
English heritage as well as drinking iced tea as I was growing up led me to my interest in the
history of tea. I became an avid tea drinker as an adult, and I love to experience different types
of tea, especially when traveling overseas. I began to experiment with infusion methods,
medicinal uses, and preservation techniques. I started a culinary and medicinal herb garden last
year with tea plants in the center. The goal of my collection is three-fold. First, it is to show that
a tea collection encompasses not only tea leaves, but items needed to make tea such as infusers
and tableware such as teacups and saucers. Second, my goal is to show that tea is part of our
national American heritage and has permeated popular culture. Lastly, tea has a ritual and
spiritual component that has captured human imagination. For these reasons, my collection
represents these elements to tell the story of tea in our culture."
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: Wendy Burkett

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the csv file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: teacollection

##########
# Site/Organization Branding 
#   Uncomment these and enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#
# organization-name: "Center for Digital Inquiry and Learning (CDIL)"
# organization-link: https://cdil.lib.uidaho.edu/
# organization-logo-banner: https://cdil.lib.uidaho.edu/storying-extinction/assets/img/cdil.png
# organization-logo-nav: https://cdil.lib.uidaho.edu/assets/img/logo.png

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md]
# compress CSS output
sass:
  style: compressed
